## Example

$H_0$: $\mu = 10$

$H_1$: $\mu \ne 10$

```{r}
mu0 <- 10 # null hypothesis
s <- 3 # sample stdev
n <- 20
xbar <- 8.5 # sample mean

stderr <- s / sqrt(n)
(t <- (xbar - mu0) / stderr)

(pvalue <- 2 * (1 - pt(abs(t), n - 1)))

alpha <- 0.05

pvalue < alpha
```

Reject $H_0$ at $\alpha = 0.05$

## Sample

```{r}
sample.mean <- replicate(n = 100, expr = {
    mean(rnorm(n=20, mean=10, sd=3))
})
summary(sample.mean)
```

## Scores Example

```{r}
scores <- read.csv("https://raw.githubusercontent.com/njlytal/MATH314/main/scores.csv")
```

### Plot Data

```{r}
library(ggplot2)
ggplot(
    data=scores,
    aes(x = new.score - old.score)
) + geom_histogram(bins = 6)
```

### Confidence Interval

```{r}
xdiff <- mean(scores$new.score - scores$old.score)
n <- min(length(scores$new.score), length(scores$old))
sdiff <- sd(scores$new.score - scores$old.score)
alpha <- 0.05
```

### Margin of Error

Assuming two-tailed test

```{r}
tstar <- qt(1 - alpha / 2, n - 1)
stderr <- sdiff / sqrt(n)
margin_err <- tstar * stderr
(ci <- c(xdiff - margin_err, xdiff + margin_err))
```

### Hypothesis Test

$H_0$: $\mu_{\text{diff}} = 0$

$H_1$: $\mu_{\text{diff}} \ne 0$

```{r}
mu0 <- 0 # null hypothesis value
(t <- (xdiff - mu0) / stderr)
(pvalue <- 2 * (1 - pt(abs(t), n - 1)))
pvalue < alpha
```


